spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  application.name: 'mortgage'
  h2:
    console:
      enabled: true
      path: /h2
      settings.trace: false
      settings.web-allow-others: false

  datasource:

    url: jdbc:h2:file:~/data/mortgage
    username: sa
    password: sa
    driverClassName: org.h2.Driver
